apiVersion: v1
kind: Pod
metadata:
  name: allowed-pod
  namespace: yr-opa-demo
  labels:
    owner: yr
spec:
  containers:
    - name: nginx
      image: 951734991809.dkr.ecr.ap-south-1.amazonaws.com/myapp:v1