apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-fail
  namespace: hv-opa-demo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
