apiVersion: v1
kind: Pod
metadata:
  name: compliant-pod
  namespace: hv-opa-demo
  labels:
    env: dev
spec:
  containers:
    - name: nginx
      image: nginx:1.27.5
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
        privileged: false