apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deny-default-ns-demo-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/yash2418/opa-on-eks
    targetRevision: feature/HV_Opa-Policies
    path: Examples/demo/

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
