apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8sallowedregistries
spec:
  crd:
    spec:
      names:
        kind: K8sAllowedRegistries
      validation:
        openAPIV3Schema:
          type: object
          properties:
            registries:
              type: array
              items:
                type: string

  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8sallowedregistries

        violation[{"msg": msg}] {
          container := input.review.object.spec.containers[_]
          not startswith_any(container.image, input.parameters.registries)

          msg := sprintf(
            "Container image '%v' is not from an approved registry",
            [container.image]
          )
        }

        violation[{"msg": msg}] {
          container := input.review.object.spec.template.spec.containers[_]
          not startswith_any(container.image, input.parameters.registries)

          msg := sprintf(
            "Container image '%v' is not from an approved registry",
            [container.image]
          )
        }

        startswith_any(image, registries) {
          registry := registries[_]
          startswith(image, registry)
        }